import { PublicKey } from "@solana/web3.js"

export const PROGRAM_IDS = {
 RAYDIUM_PROGRAM_ID: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
 RAYDIUM_CLMM_PROGRAM_ID: "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK",
 RAYDIUM_CPMM_PROGRAM_ID:"CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C",
 RAYDIUM_LAUNCHPAD_PROGRAM_ID: "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj",
 METEORA_AMM_PROGRAM_ID: "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB",
 METEORA_DLMM_PROGRAM_ID: "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo",
 METEORA_DAMM_V2_PROGRAM_ID: "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG",
 METEORA_DBC_PROGRAM_ID: "dbcij3LWUppWqq96dh6gJWwBifmcGfLSB5D4DuSMaqN",
 ORCA_WHIRLPOOL_PROGRAM_ID: "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc",
 PUMP_FUN_PROGRAM_ID: "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P",
 PUMP_SWAP_PROGRAM_ID: "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA",
 MOONSHOT_PROGRAM_ID: "MoonCVVNZFSYkqNXP6bxHLPL6QQJiMagDL3qcqUQTrG",
 HEAVEN_PROGRAM_ID: "HEAVENoP2qxoeuF8Dj2oT1GHEnu49U5mJYkdeC8BAX2o",
 SUGAR_PROGRAM_ID: "deus4Bvftd5QKcEkE5muQaWGWDoma8GrySvPFrBPjhS",
 BOOP_FUN_PROGRAM_ID: "boop8hVGQGqehUK2iVEMEnMrL5RbjywRzHKBmBE7ry4"
}

export const PROGRAM_IDS_PUBLIC_KEYS = {
 ...PROGRAM_IDS,
 ...Object.fromEntries(Object.entries(PROGRAM_IDS).map(([key, value]) => [key, new PublicKey(value)]))
}
